logging.level.org.springframework.validation=DEBUG
logging.level.org.hibernate.validator=DEBUG
server.port=8080
token=eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJkYW1zIiwiaWF0IjoxNzMwNTY3NzgyLCJleHAiOjE3MzA2NTQxODJ9.pKT834V0fDWNLWyW9IQJ2Fj5zNjYuVxTlauyAj70S1I8jM4f6q61PFaHOKljg852