spring:
  data:
    mongodb:
      uri: mongodb+srv://fitastic:admin@cluster0.ue4gs.mongodb.net/fitastic?retryWrites=true&w=majority
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
