spring:
  data:
    mongodb:
      uri: mongodb+srv://fitastic:admin@cluster0.ue4gs.mongodb.net/fitastic?retryWrites=true&w=majority
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
              MongoTemplate: 'DEBUG'
application:
  security:
    jwt:
      secret-key: 4bb6d1dfbafb64a681139d1586b6f1160d18159afd57c8c79136d7490630407c
      access-token-expiration: 86400000
      refresh-token-expiration: 604800000
